#!/usr/bin/env bash
# scripts/vendor.sh — vendor all workspace dependencies for reproducible,
# offline builds (supply-chain integrity, §19.2).
#
# Produces ./vendored with a .cargo/config.toml that redirects crates.io to the
# local mirror. CI and air-gapped build hosts then build with
#   cargo build --offline --locked
#
# Requires network access the FIRST time it is run (to fetch crates).
set -euo pipefail

cd "$(dirname "$0")/.."

echo "Vendoring dependencies into ./vendored ..."
cargo vendor --locked vendored > .cargo/config.toml

# Ensure the generated config also pins the registry to the vendored dir.
cat >> .cargo/config.toml <<'EOF'

# Generated by scripts/vendor.sh — redirects crates.io to the local vendored
# mirror for offline / reproducible builds.
[registries.crates-io]
index = "sparse+https://github.com/rust-lang/crates.io-index"
EOF

echo "Done. Verify offline build with: cargo build --offline --locked"
